sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --upload --pdf PSTN-004.pdf --lsstdoc PSTN-004.tex --env=travis --ltd-product pstn-004"
env:
  global:
    - secure: "JrA28qnN47MM7K4Kpqf9DUqKBgcePcyzf9/nndpY4ZppS9wPl6QZINYNBrsUfMm0SxaY9ZBIWZhoFoFuh0FMzXFwx/urKoA0MeKBsb7zIIMqw54A50F3pvhiJj0GER0OirkgDkqHD2O1DObUnT3hbcJgaODlTevLJffMiKbZ29PcfsoiJGXC3FTGLw4wRL5A4L3W/8yQQCOtsU49D22/RIGkPG0DB1Twb4W8N9VxtzdMpHB1qpwhPh20v3NoFGcuGYdvUPNLk8gVqxZ+5dt+Bv9ylDOPmyea6SYpLlcFNtJQWD9F9nQZEubQYM6jSGyD1aH9OCobxZIcCyDJI19WhEhGZ+LIQFZAo9vSFahmzGEOUdz/jbrv+NsR9To/I9wFeqbnDP2xx0+McFX2rrNv5e4TenhsQ0WuF6ELLR/1s0RAfdMhsq68oUqRyUlmaW7CzNuJppsawfiX4SOGdTRUYxQvTep/tzO9N/DctWpgGgjNBStqMbeLvDuhxRlQ631hoVI57CdH7qoPoLevqPvJ5HjGHqmgv+giNdz7L+bSUnIZXhoyOBPzBcYvE0olrEjCAdsvixDiYWGNz9jfuQPgu1DHJFWY4ffBvDDVz+TdhrkCvj2Oix32zPtBLrkZ3Q2Oxu2SFIB8pg5Y/JteU+tA8GJDMmht0UiYuRjxMvG8hMU="
    - secure: "bQV2gjXyjim5I1vyYp3dF1pqT/RyM8CRO9NYad/aG5tlFl2itm2ejProbKduRRnSKjqBEvYoN6hnfajxde07nbDjSi2hbThLk09mJ5EY6rBkst/bmDJmatRF9w2HPdV3RdEqb5LkcGZkbTquPpVg37vxivKVoOaopVYSQ/njA02O7u1Qh9uqz2ZvZDMZi+tRzVbOHoGzSQsBfVV7kIjvEHweKhTIGQALCbPWZk4fR2guKw5usZYCiUEXddPSjcLcZB0e7Rr1hYOjwTZ97ORJUmhP4RofMIulWlLuX9nmZ5DqHtbdmgIqEwlu1ClfdNyW+PNdxmlo9l8ZZjZuF588cWy3EbXkirHHs8Q8ZAXYntDn7A3FqGBO2TMy5XL/VqE9FHyXAbPWBmrGg0hsEsicDpIP9VwM7cTjbdsbMqvvmwc54HYCz9Cx0qaV0eg0EKN2j69cO7eRdxEbZB3CT4GSDGNt9LztRhM/QqZTslcy16bHsy/mO8Jhf5cQs24hHQ+S1GcUEb0ufbmczvdgUcp6wg4tzLkFkm0c11DZVp7BF6rpv0Q9cytbPKIY1iU8HResCJNZGZtSoEHr8brMLrMamdtvv9LqyDRdGkyA0ovph+ZaSz0Ttev7vrKLQOYDrQD9kfN3AMhu7uSE37gvtA37NcDk+Y8egXwHN/TInx2D004="
